creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - age1fnle7w46h40zap4efs52lczmt47zg0h5waml3r3jmqgtkwdxep0q89wz27
          - age1cwt78nzh2d625uhw3ug9ah4r0wum3jcl5xdjsfnjpm272p7s2dtsc003qd
          - age1wx6evf3xyxzj7kqxaq3z0ex0glfuvk3v7c22rexw7gc7fr73zdxsmt0azm
