#cloud-config
# RustDesk Server Pro — hbbs + hbbr via Docker Compose (host networking).
# License is entered in the web console (https://<ip>:21114), not here.

package_update: true
package_upgrade: false

packages:
  - docker.io
  - docker-compose-v2

write_files:
  - path: /etc/rustdesk/compose.yml
    permissions: '0644'
    content: |
      services:
        hbbs:
          container_name: hbbs
          image: docker.io/rustdesk/rustdesk-server-pro:latest
          command: hbbs
          volumes:
            - /var/lib/rustdesk:/root
          network_mode: "host"
          depends_on:
            - hbbr
          restart: unless-stopped

        hbbr:
          container_name: hbbr
          image: docker.io/rustdesk/rustdesk-server-pro:latest
          command: hbbr
          volumes:
            - /var/lib/rustdesk:/root
          network_mode: "host"
          restart: unless-stopped

runcmd:
  - mkdir -p /var/lib/rustdesk
  - systemctl enable --now docker
  - docker compose -f /etc/rustdesk/compose.yml up -d
